# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-12 21:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='upload/logos/')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_cases', models.TextField()),
                ('industry', models.CharField(max_length=100)),
                ('vertical', models.CharField(max_length=100)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SalesforceCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='upload/salesforce/')),
                ('name', models.CharField(max_length=100)),
                ('descriptor', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='noname',
            name='clouds',
            field=models.ManyToManyField(related_name='no_names', to='simulation.SalesforceCloud'),
        ),
        migrations.AddField(
            model_name='noname',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_names', to='simulation.Customer'),
        ),
        migrations.AddField(
            model_name='asset',
            name='no_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='simulation.NoName'),
        ),
    ]
