# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-11 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=100)),
                ('csv_integers', models.CommaSeparatedIntegerField(max_length=200)),
                ('logo', models.ImageField(upload_to='upload/logos/')),
                ('text_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='upload/related/')),
                ('dummies', models.ManyToManyField(related_name='images', to='dummy.DummyModel')),
            ],
        ),
        migrations.AddField(
            model_name='charfieldmodel',
            name='dummy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_chars', to='dummy.DummyModel'),
        ),
    ]
